/* eslint-disable */
// @ts-nocheck
import {
  loadMovieWatchlist,
  loadPlaylist,
  loadPlaylistSession,
  loadSettings,
  loadShowsListProgress,
  loadWatchlist,
} from './storage';

export const appState = {
  settings: loadSettings(),
  watchlistStore: loadWatchlist(),
  movieWatchlistStore: loadMovieWatchlist(),
  playlistStore: loadPlaylist(),
  playlistSession: loadPlaylistSession(),
  showsListProgress: loadShowsListProgress(),
  showsListProgressOrder: -1,
  showsListSeenCandidate: null,
  showsListSeenCandidateOrder: -1,
  showsListSessionTouched: false,
  showsListManualMarkerSet: false,
  showsListObserver: null,
  showsListMutationObserver: null,
  showsListRefreshScheduled: false,
  showsListObservedCards: new WeakSet(),
  domBootstrapped: false,
  uiBootAttempts: 0,
  fullscreenTriggered: false,
  lastKnownUrl: location.href,
  watchlistRefreshPromise: null,
  watchlistBusy: false,
  watchlistMessage: '',
  watchlistMessageTone: 'muted',
  lastTrackedEpisodeSignature: '',
  ntfyRemoteStatus: 'disabled',
  ntfyRemoteMessage: '',
  ntfyLastNotificationAt: 0,
  ntfyRemoteTabId: `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`,
  ntfyRemoteClaimTimer: 0,
};
